models.py
from datetime import datetime
from time import time
from app import db
import re
from flask_security import UserMixin, RoleMixin

def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


posts_tags = db.Table('posts_tags',
                    db.Column('post_id', db.Integer,
                    db.ForeignKey('post.id')),
                    db.Column('tag_id', db.Integer,
                    db.ForeignKey('tag.id'))
)

roles_users = db.Table('roles_users',
                        db.Column('user_id', db.Integer,
                        db.ForeignKey('user.id')),
                        db.Column('role_id', db.Integer,
                        db.ForeignKey('role.id'))
)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    tags = db.relationship('Tag', secondary=posts_tags,
    backref=db.backref('posts'), lazy='dynamic')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time))


    def __repr__(self):
        return f'<Post id : {self.id}, title : {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)
        else:
            self.slug = str(int(time))

    
    def __repr__(self):
        return f'<Tag id : {self.id}, title : {self.title}>'

class User(db.Model, UserMixin):
    id=db.Column(db.Integer, primary_key=True)
    email=db.Column(db.String(100), unique=True)
    password=db.Column(db.String(255))
    active=db.Column(db.Boolean)
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(100), unique=True)

posts/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask, redirect, url_for, request
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin, AdminIndexView
from flask_admin.contrib.sqla import ModelView

from flask_security import SQLAlchemyUserDatastore, Security, current_user

from config import Config



app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)

from models import *

migrate = Migrate(app, db)
manager = Manager(app)


manager.add_command('db', MigrateCommand)

class AdminMixin:
	def is_accessible(self):
		return current_user.has_role('admin')

	def inaccessible_callback(self, name, **kwargs):
		return redirect(url_for('security.login', next=request.url))

class AdminView(AdminMixin, ModelView):
	pass

class HomeAdminView(AdminMixin, AdminIndexView):
	pass

class BaseModelView(ModelView):
	def on_model_change(self, form, model, is_created):
		if is_created:
			model.generate_slug()

		return super().on_model_change(form, model, is_created)

class PostAdminView(AdminMixin, BaseModelView):
	form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
	form_columns = ['title']

# Admin manger
admin = Admin(app, 'FlaskApp', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask-security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db
import views
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')
# localhost:5000/blog



if __name__=="__main__":
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required
from models import Post, Tag
from .forms import PostForm
from app import db
posts = Blueprint('posts', __name__, template_folder='templates')



@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    form = PostForm()

    if request.method == "POST":
        title = request.form.get("title")
        body = request.form.get("body")

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print("Very long traceback")
        return redirect(url_for('posts.post_detail', slug=post.slug))
    return render_template('posts/post_create.html', form=form)





# localhost:5000/blog
@posts.route('/')
def posts_list():

    q = request.args.get('q')

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    else:
        posts = Post.query.order_by(Post.created.desc())


    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    pages = posts.paginate(page=page, per_page=1)

    return render_template('posts/posts.html', posts=posts, pages=pages)

@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    return render_template('posts/post_detail.html', post=post)


@posts.route('/tags/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    return render_template('posts/tag_detail.html', tag=tag)


@posts.route('/<slug>/edit', methods=['GET', 'POST'])
@login_required
def post_update(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()

    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template("posts/edit.html", post=post, form=form)

views.py
from flask import render_template

from app import app

@app.route('/')
def index():
    return render_template('index.html')

@app.errorhandler(404)
def page_not_found(e):
	return render_template('errors/404.html')

posts/templates/posts/edit.html
{% extends 'base.html' %}

{% block title %} Update Post {% endblock %}


{% block content %} 
    <h1>Update post</h1>
    <form action="{{ url_for('posts.post_update', slug=post.slug) }}" method="post">
        {% for field in form %}
            <div class="mb-3">

                {{ field.label(class="form-label") }}

                {{ field(class="form-control")  }}

            </div>
        {% endfor %}
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

posts/templates/posts/includes/card.html
<div class="card mb-4">
    <div class="card-header">
    {{ post.created.date() }}
    </div>
    <div class="card-body">
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="card-title">{{ post.title }}</a>
    <p class="card-text">{{ post.body }}</p>
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}" class="btn btn-primary">Read more...</a>
    </div>
    {% if post.tags.count() %}
    <div class="card-footer text-muted">
        {% for tag in post.tags %}
            <a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}">
                <span class="badge bg-info text-white">{{ tag.title }}</span>
            </a>
        {% endfor %}
    </div>
    {% endif %}
</div>

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %} Create New Post {% endblock %}


{% block content %} 
    <h1>Create new post</h1>
    <form action="{{ url_for('posts.post_create') }}" method="post">
        {% for field in form %}
            <div class="mb-3">

                {{ field.label(class="form-label") }}

                {{ field(class="form-control")  }}

            </div>
        {% endfor %}
        <button class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} {{post.title}} {% endblock %}


{% block content %} 
<h1>{{post.title}}</h1>
    <div class="">
        {{post.body}}
    </div>
{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}

{% block title %} Post list {% endblock %}


{% block content %} 
<h1>Post</h1>
   {% for post in pages.items %}
        {% include 'posts/includes/card.html' %}
   {% endfor %}


    <nav aria-label="...">
        <ul class="pagination">
        <li class="page-item {% if not pages.has_prev %}disabled{%endif%}">
            <a class="page-link" href="./?page={{ pages.prev_num }}">Previous</a>
        </li>

        {% for page in pages.iter_pages() %}
        <li class="page-item {% if page == pages.page %} active {% endif %}">
            <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
        </li>
        {% endfor %}

        <li class="page-item {% if not pages.has_next %}disabled{%endif%}">
            <a class="page-link" href="./?page={{ pages.next_num }}">Next</a>
        </li>
        </ul>
    </nav>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %} Post view "{{ tag.title }}" {% endblock %}


{% block content %} 
    <h1>Post with the "{{tag.title}} tag"</h1>   
    {% for post in tag.posts %}
        {% include 'posts/includes/card.html' %}
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{ url_for('index') }}">Flask App</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('posts.posts_list') }}">Blog</a>
              </li>
              {% if current_user.has_role('admin') %}
                <li class="nav-item">
                  <a class="nav-link"  href="/admin">Admin</a>
                </li>
              {% endif %}
            </ul>
            <form class="d-flex" method="GET">
              <input class="form-control me-2" type="search" placeholder="Search" name="q">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


      <div class="container">
          <div class="row">
            <div class="col-9 mx-auto">
              {% block content %}{% endblock %}
            </div>
          </div>
      </div>

      {% if current_user.is_authenticated %}
        <div class="login-panel">
          <a href="{{ url_for('security.logout') }}" class="btn btn-light">Logout</a>
        </div>
      {% else %}
         <div class="login-panel">
          <a href="{{ url_for('security.login') }}" class="btn btn-light">Login</a>
        </div>
      {% endif  %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}


{% block content %}
    <h1>Hello World.</h1>
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}


{% block content %} 

	{% from "security/_macros.html" import render_field_with_errors, render_field %}
	{% include "security/_messages.html" %}
	<h1>{{ _('Login') }}</h1>
	<form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
	  {{ login_user_form.hidden_tag() }}
	  {{ render_field_with_errors(login_user_form.email, class="form-control") }}
	  {{ render_field_with_errors(login_user_form.password, class="form-control") }}
	  {{ render_field_with_errors(login_user_form.remember, class='form-check-input') }}
	  {{ render_field(login_user_form.next) }}
	  {{ render_field(login_user_form.submit, class="btn btn-success") }}
	</form>
	{% include "security/_menu.html" %}

{% endblock %} 